// <auto-generated />
namespace Reflect.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Addmigrationc : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addmigrationc));
        
        string IMigrationMetadata.Id
        {
            get { return "201701211131351_Add-migration -c"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
